name: EssentialsBackPlugin
main: com.example.backplugin.BackPlugin
version: 1.0.0
api-version: 1.21
author: munayan6969
description: A simple Paper plugin that adds a configurable /back command.

commands:
  back:
    description: Teleports you to your last location.
    usage: /back
    permission: essentials.back

permissions:
  essentials.back:
    description: Allows the player to use /back.
    default: true
