name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Build with Maven
      run: mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: EssentialsBackPlugin
        path: target/EssentialsBackPlugin-1.0.0.jar
